### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 37Block** [256shadesofgrey/eso-light-attack-weave#18] opened 2023-01-07 23:06 UTC
i downloaded the script and the app ( auto hotkey ) and i run the script but there is nothing happening, it doesn't suspend on tab or do anything, i see it's green icon but it simply doesn't function and yes, my keyboard is english

**Comment by 256shadesofgrey** [comment] 2023-01-08 05:17
Is the game window in focus when you try it? Because if not, it won't do anything. That's intentional to prevent messing with other programs you might be interacting with.

**Comment by 37Block** [comment] 2023-01-08 13:17
> Is the game window in focus when you try it? Because if not, it won't do anything. That's intentional to prevent messing with other programs you might be interacting with.

yes the game window is in focus, tried fullscreen/windowed during which i ran the script and nothing, it doesn't even respond to me pressing tab to activate it .

**Comment by 256shadesofgrey** [comment] 2023-01-08 20:55
Try starting the script after launching the game. There was a period of time where the order was relevant, maybe another game update made it relevant again (I haven't played the game in a while, so I have not used the script recently).

If that doesn't work, try commenting out [this line](https://github.com/256shadesofgrey/eso-light-attack-weave/blob/ff5104aa2bdd9c0ac463a1683cacf3c75eb2a42d/eso-light-attack-weave.ahk#L121)  (put a semicolon in front of it, like in the line above) and see if that changes anything. This will make it so that the game does not have to be in focus for the script to work. Then you can try out if it does anything in any other program (for example a text editor). If this doesn't work, the issue is with your system, not with the script or the game.

**Comment by ChengYuAlex** [comment] 2023-02-05 17:19
same. nothing happened

**Comment by 256shadesofgrey** [comment] 2023-02-05 17:32
> same. nothing happened

When you press tab, does the icon in the tray change from an S to an H or vice versa?

**Comment by 256shadesofgrey** [comment] 2023-08-26 16:38
I'm closing this issue since I'm not getting any details on what exactly isn't working.

**Closed by 256shadesofgrey** 2023-08-26 16:38 UTC
